version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api
    ports:
      - "9000:9000"
    restart: always
    #volumes:
     # - .env:/api/.env